--- 
- hosts: 172.31.84.114 
  become: yes 
  tasks: 
  - name: execute linux command directly 
    command: hostname -f 
    register: myresult 

  - name: i want to display first task result 
    debug: 
      msg: "{{myresult}}"  