--- 
- hosts: all 
  tasks: 
  - name: insatll git 
    apt: 
     name: git 
     state: present 

     
  - name: install wget 
    apt: 
     name: wget 
     state: present 

  - name: install tree  
    apt: 
     name: tree  
     state: present
   
       