--- 
- hosts: 172.31.84.114
  become: yes 
  tasks: 
  - include_tasks: myfiles.yml 
  - name: create a folder 
    file: 
     path: /home/ubuntu/myfolder
     state: directory 
  - name: i want to copy files 
    copy: 
      src: mystaticfile
      dest: /home/ubuntu/mystacticfile.txt